### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by julianfairfax** [LeanderBB/you-have-mail#11]
I have created an issue for this app to be added to F-Droid: https://gitlab.com/fdroid/rfp/-/issues/2419. Do you oppose this?

**Comment by LeanderBB** [comment]
Hey Julian,

I don't oppose at all, it was always my plan to get this into F-droid :).

Thanks for the help.

**Comment by LeanderBB** [comment]
@julianfairfax https://f-droid.org/packages/dev.lbeernaert.youhavemail/ :)
