### ISSUE TITLE
App asks for CAPCHA for security reasons

### ISSUE THREAD

**Issue by BalooRJ1** [LeanderBB/you-have-mail#12]
Hello,

When attempting to login to my Protonmail accoumt use this app with GrapheneOS, I am given an error message in the app asking for completion of a CAPCHA. But it does not appear the app supports a CAPCHA. Any thoughts as to a fix? Thank you very much.

**Comment by LeanderBB** [comment]
Hey, have you tried to use the "Proton Mail V-Other" backend? That seems to solve the capcha issue for some folks.

**Comment by BalooRJ1** [comment]
Thanks for the quick reply. Unfortunately, the other login option gives me "Network Request Failed."

**Comment by LeanderBB** [comment]
Regarding the capcha, it is sadly not something I can fix since I can't reproduce it :/.

That being said, the other backend has been known to work and used to circumvent this.

Could you share the logs from the application when the request fails so I can take a look?

**Comment by BalooRJ1** [comment]
How would I go about accessing logs?

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by LeanderBB** [comment]
You can follow one of the suggestions listed here:
https://www.xda-developers.com/how-to-take-logs-android/

**Comment by LeanderBB** [comment]
@BalooRJ1 do you still have network issues and/or managed to get hold of the logs?

**Comment by LeanderBB** [comment]
Is it possible you have the old two password system enabled for your account?

**Comment by LeanderBB** [comment]
@Wjfxi, did you try to use the Proton V-Other Backend? It's known to not request captchas.

If you did and you ran into a network request error, do you have a proton account with two password mode?

**Comment by theAkito** [comment]
@Wjxfi

> I don't know about the rest.


https://github.com/LeanderBB/you-have-mail/issues/13#issuecomment-1567030265

**Comment by dailyherold** [comment]
Greetings. I'm getting the `Network request failed` error as well. I do not have two password mode enabled, but do have MFA enabled, which seems to be the issue. In my Proton Mail logs I see the following security event log:

> Sign in success (awaiting second factor)

**Comment by LeanderBB** [comment]
Hey, do you think you could provide the app logs?

There is support for TOTP codes, but not for FIDO/yubi keys. The former does not cause network request errors though.

**Comment by LeanderBB** [comment]
@dailyherold Does this happen after you submit the username + password or after you input 2FA/TOTP ?

**Comment by dailyherold** [comment]
Sorry for delay @LeanderBB, I have a security key ([onlykey](https://onlykey.io/)) registered, so based on your comment that must be it. I'll remove key and re-test to confirm.

**Comment by dailyherold** [comment]
Yup, got it working by removing security key. Might open an issue simply for tracking, no pressure to work on.

**Comment by LeanderBB** [comment]
@dailyherold Thanks so much for digging deeper into this :pray:

**Comment by LeanderBB** [comment]
Good news everybody, I finally managed to trigger the captcha request.

[v0.9.0](https://github.com/LeanderBB/you-have-mail/releases/tag/v0.9.0) now supports solving Proton Captchas.

If there is an issue related to this new feature, please open a separate ticket, thanks.
