### ISSUE TITLE
Feature Request: Mailbox password support (two password mode)

### ISSUE THREAD

**Issue by licaon-kter** [LeanderBB/you-have-mail#13]
...is it available or not?

No notifications in my testing of such an account.

**Comment by LeanderBB** [comment]
Hey @licaon-kter, could you be a bit more specific? I'm not sure what you are referring to.

**Comment by licaon-kter** [comment]
_Oh kids these days, they don't know the hurdles we had back in the day..._

https://proton.me/support/switch-two-password-mode

**Comment by LeanderBB** [comment]
Ah, I see. I wasn't even aware this was a thing :sweat_smile:

I currently don't have support for this. The accounts I tested with are only using single password mode.

I'll see what can be done to enable this.

**Comment by LeanderBB** [comment]
@licaon-kter I created a new account with 2 password mode and I am able to receive the new email notifications. 

Could you please try again? Perhaps, the default poll interval was too long? You can shorten it in the settings.

**Comment by LeanderBB** [comment]
@theAkito, based on the thread reactions, do you happen to have a 2-password mode account? If so, could you let me know if this also works for you?

**Comment by licaon-kter** [comment]
So you entered both passwords?

**Comment by LeanderBB** [comment]
I just used the login password. 

I initially assumed that perhaps there was perhaps a second request that had to be made to unlock these features. This does not seem to be the case. I check some of Proton Apps source code and it the 2nd password is only required if you need to decrypt the messages.
