### ISSUE TITLE
Set up instructions

### ISSUE THREAD

**Issue by ViktorKahu** [LeanderBB/you-have-mail#14]
Please shed some light on how to use it. Not everyone knows what a proxy is or how to find the data required for the setup.

Thanks in advance.

**Comment by LeanderBB** [comment]
Hey @ViktorKahu, that's a good point. Thanks for bringing this up.

I will make this step clearer as soon as I'm able.

In the mean time, the proxy is an optional setup step that is not required for normal use of the app. It was added at the request of another user who has a more advanced network setup.

If you don't need this , you can simply leave the Use Proxy​ toggle disabled and click next.

**Comment by ViktorKahu** [comment]
Thanks.

**Comment by LeanderBB** [comment]
Proxy configuration clarified in v0.8.0 release.
