### ISSUE TITLE
Add UnifiedPush support (ntfy, nextpush, up-fcm, etc...)

### ISSUE THREAD

**Issue by amosstevens** [LeanderBB/you-have-mail#15]
It could be useful to add ntfy support for the push notification to save battery, especially for those that already have several application that using it (element, fedilab, find my device etc...)

**Comment by LeanderBB** [comment]
Hey @amosstevens.

As far as I can tell, that would require a standalone binary that runs on a server somewhere that then integrates with the nfty service.

Is this what you had in mind?

------- Original Message -------

**Comment by amosstevens** [comment]
yes, is needed a binary hosted somewhere, but there are already several public instances that someone can use, or the official one

https://docs.ntfy.sh/integrations/?h=servers#alternative-ntfy-servers

**Comment by LeanderBB** [comment]
I can't promise an ETA, but I will certainly look into it :)

**Comment by p1gp1g** [comment]
I think your asking support for [UnifiedPush](https://unifiedpush.org) : that's the protocol used by ntfy to forward notifications to other apps. (ntfy is an *UnifiedPush distributor*).

By supporting UnifiedPush you'll let users to use your app with the push system they want : ntfy, NextPush, Conversation (or fork) or any other.

For more information, you can read this blog post: https://f-droid.org/2022/12/18/unifiedpush.html

So, I think you should edit this issue title :) (/ntfy/UnifiedPush/)

**Comment by LeanderBB** [comment]
I'm closing this ticket. To keep up to date with this topic please follow [this issue](https://github.com/LeanderBB/you-have-mail-cli/issues/1).
