### ISSUE TITLE
Click notification to open mail

### ISSUE THREAD

**Issue by ViktorKahu** [LeanderBB/you-have-mail#17]
First of all, thanks for a working solution, shame on protonmail for ignoring user wishes and dragging it out for years.

Some ideas for future versions:

Is there any way to:

1) Open Protonmail by clicking the you have mail notification
2) For the notification to clear once clicked.

Cheers.

**Comment by LeanderBB** [comment]
Hey,

This functionality is already implemented. If you have the proton mail APK installed it should open the app.I have tested this on Graphene OS.

If you don't, the notification should dismiss itself.

**Comment by LeanderBB** [comment]
Closed due to lack of activity.
