### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [LeanderBB/you-have-mail#18]
...in a repro way

ref: https://monitor.f-droid.org/builds/log/dev.lbeernaert.youhavemail/21#site-footer

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/b6cafda9a58a5ce92fd6e5e53eda8af4f34cf2e3

**Comment by LeanderBB** [comment]
I'm not sure what happened :/. I used the exact same build environment from the v0.7.2 release.

Is it possible to get the apk that was produced in that build step from fdroid so I can investigate?

**Comment by licaon-kter** [comment]
The autoupdate CI failed too the other day https://gitlab.com/fdroid/fdroiddata/-/jobs/4409146574#L2475 so you can grab its apk: https://gitlab.com/fdroid/fdroiddata/-/jobs/4409146574/artifacts/file/tmp/dev.lbeernaert.youhavemail_21.apk

**Comment by linsui** [comment]
> info: latest update on 2023-06-01, rust version 1.70.0 (90c541806 2023-05-31)

Looks like we failed pining the rust version.

**Comment by licaon-kter** [comment]
Thanks

**Comment by LeanderBB** [comment]
Thanks for submitting the patch, much appreciated :)

**Comment by LeanderBB** [comment]
@licaon-kter Thanks for the report, looks like there is a mismatch with the go artifacts.

I does look like the go version is the same with image i used to build the binary:
`go version go1.22.7 linux/amd64`.

I will try to see if there is another mismatch somewhere.

**Comment by licaon-kter** [comment]
Sure, many use it

**Comment by LeanderBB** [comment]
@licaon-kter Is it possible that some other build tree conflict happened since I notice there are 2 other packages being built in that log output, or is that not possible?

**Comment by licaon-kter** [comment]
It is possible

**Comment by LeanderBB** [comment]
Resolved: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/17646
