### ISSUE TITLE
Where are the login data saved?

### ISSUE THREAD

**Issue by LeOS-GSI** [LeanderBB/you-have-mail#20]
Are all data stored only local on my device?  Or are there any connections/usage of external server? 
That's very important for privacy

**Comment by LeanderBB** [comment]
Hey @LeOS-GSI, the session tokens are stored encrypted on the device using [Android's Encrypted Shared Preference](https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences) at the moment.
