### ISSUE TITLE
[feature request] make the password visible and hideable.

### ISSUE THREAD

**Issue by gbdomubpkm** [LeanderBB/you-have-mail#22]
First, thank you for your work on this useful app.

For entering the password of an email account , this feature  is useful. Entering the password is a source of errors and i don't like copying passwords to the clipboard.. Thank you.

**Comment by LeanderBB** [comment]
Released as part of [v0.11.0](https://github.com/LeanderBB/you-have-mail/releases/tag/v0.11.0).
