### ISSUE TITLE
Upstreaming

### ISSUE THREAD

**Issue by julianfairfax** [LeanderBB/you-have-mail#24]
Since notifications without Google Play Services are possible in this separate app, surely this same implementation, or one very similar to it would also work in the [Proton Mail app](https://github.com/ProtonMail/proton-mail-android) itself?

Proton Mail have said multiple times over the years that they were working on notifications without Google Play Services, but they have still not shared any of this progress with the community.

That's why I'm opening this issue here, to see what can be done by you, or maybe by others, to add this support ourselves.

Benefits of having this support in the app itself:
- Would only have to install one app
- Would only have to log into one app
- When clicking on a You Have Mail notification, it opens the Proton Mail app, but leaves a You Have Mail window in the recent apps. This wouldn't be an issue if the Proton Mail app itself were the one sending the notification and opening itself upon clicking it.

Thanks for this essential app!

**Comment by LeanderBB** [comment]
Hey @julianfairfax, I understand your point of view. I personally, also wish that Proton would implement this feature. My current understanding of the situation is that they are in the middle of a rewrite, so anything that could be done for the existing code base may very well be dead on arrival. 

Additionally, there is also the issue that the current state of the App runs well on Android distributions that closely behave the way "vanilla" Android does. During my research for this app, I have found reports that certain brands modify the Android runtime in a certain way that would complicate or render this type of foreground process impossible. You can also read [the nfty apps](https://github.com/binwiederhier/ntfy-android/blob/main/app/src/main/java/io/heckel/ntfy/service/SubscriberService.kt)'s service comment to see all the juggling required to get that to work correctly.

Finally, I think this sort of issue is better handled on their issue tracker than mine. Aside from being able to reach more users than my issue tracker, it would, hopefully, also able attract the attention of more experience Android devs (my app works, but i'm not sure how good/correct the underlying code is :sweat_drops:). Feel free to mention me in the conversation, I'm more than happy to participate in that discussion.

**Comment by julianfairfax** [comment]
I agree with you about the code-related stuff.

> Finally, I think this sort of issue is better handled on their issue tracker than mine. Aside from being able to reach more users than my issue tracker, it would, hopefully, also able attract the attention of more experience Android devs. Feel free to mention me in the conversation, I'm more than happy to participate in that discussion.

However, this is not possible. They disabled issues: https://github.com/ProtonMail/proton-mail-android/issues

**Comment by LeanderBB** [comment]
Well, that's unfortunate.

I would recommend revisiting this topic once the new app is released.

For more immediate actions, I would have suggested opening the discussion on Reddit (or some other channel) but that will probably also not lead to any fruitful developments as the usual response tends to be "after the rewrite is complete".
