### ISSUE TITLE
log out at every reboot

### ISSUE THREAD

**Issue by citizenserious** [LeanderBB/you-have-mail#25]
hi, at first thank you for the app. 

Somehow I get logged out at every reboot.
Seems to be a problem with a "token".

Any idea on how to get more information on this issue? I do not know how to log that through a reboot.

Thanks (:

**Comment by LeanderBB** [comment]
Hey @citizenserious. Can you please attach the logs for one of these reboot cycles?

You can export the logs by clicking the gear icon and then the "Export Logs" button. 

Note: You need the latest version of the app for this.

**Comment by LeanderBB** [comment]
Closed due to lack of activity.
