### ISSUE TITLE
Ability to get notifications for mail that doesn't reach the INBOX.

### ISSUE THREAD

**Issue by Seedthis** [LeanderBB/you-have-mail#26]
Hi Leander and thank you for the work you put in that project, I was casually browsing f-droid when I noticed your app. Hard to believe it could be real as notifications not relying on GCM have been requested years ago and are still not implemented in the official protonmail app, but your solution does work well.

I have a question about future builds : **would it be possible to get notifications for new emails that aren't in the INBOX?** I'm thinking about subfolders I made for aliases, with filters so the new emails are sent directly to these subfolders and not the INBOX.

**Comment by LeanderBB** [comment]
Hey @Seedthis, in theory, if the web mail client can produce notifications for these messages, it should be possible to extend this to the App. I will try to take a look as soon as I'm able.

**Comment by Seedthis** [comment]
We do have a dedicated page to set notifications per folder here : https://account.proton.me/u/2/mail/folders-labels. These apply to the webmail and the mobile app. I guess you're already aware of that though.

**Comment by LeanderBB** [comment]
Release as part of [v0.13.0](https://github.com/LeanderBB/you-have-mail/releases/tag/v0.13.0)
