### ISSUE TITLE
security

### ISSUE THREAD

**Issue by gothmog123** [LeanderBB/you-have-mail#27]
sorry, i'd just like to know how this app fetches new emails when IMAP is not enabled on my protonmail. does it do it in a secure way?

**Comment by LeanderBB** [comment]
Hey, this app uses the same method to check for new messages as the web client.

There is no IMAP or security issues involved.

**Comment by gothmog123** [comment]
thanks, sounds great

**Comment by rafnov** [comment]
What does it mean: app uses the same method to check for new messages as the web client?
