### ISSUE TITLE
ability to decrypt pgp messages

### ISSUE THREAD

**Issue by Wjxfi** [LeanderBB/you-have-mail#28]
This can help: https://www.f-droid.org/packages/org.sufficientlysecure.keychain/
https://www.f-droid.org/packages/eu.faircode.email/
https://www.f-droid.org/packages/com.fsck.k9/

**Comment by LeanderBB** [comment]
Hey, could you elaborate a bit more on what exactly the use case is for this ticket?

**Comment by LeanderBB** [comment]
The intention of this app is just to provide a notification for incoming messages in an email account. I have no intentions of turning this into an email client.

**Comment by LeanderBB** [comment]
Then what did you ask for?

**Comment by LeanderBB** [comment]
Currently I only support proton mail as a backend. I only check some event metadata to see if a new message has arrived.

What you are proposing is to view that same new received message in the application for proton accounts?

**Comment by LeanderBB** [comment]
My original comment still applies then, this goes beyond the scope of what I am willing to support. If you want to see the decrypted emails, please install the proton mail app.

**Comment by LeanderBB** [comment]
If you need support for a new backend/service, please create a `Backend` implementation [here](https://github.com/LeanderBB/you-have-mail-common).

I do not have any intentions of adding the preview of newly received emails in this app.
