### ISSUE TITLE
Can an ad hoc manual refresh option be included?

### ISSUE THREAD

**Issue by dln949** [LeanderBB/you-have-mail#30]
My thought is this:  Suppose I have the application checking every five minutes, and 99% of the time that is just time.  But Just for this one particular moment I want it to do a check right now.  This option would allow a user to do an immediate check.

**Comment by LeanderBB** [comment]
Hey, this would certainly be possible to do. I can't promise an ETA, but I'll look into as soon as I'm able.

**Comment by LeanderBB** [comment]
Released with [v0.14.0](https://github.com/LeanderBB/you-have-mail/releases/tag/v0.14.0).
