### ISSUE TITLE
not compatible with 32bits/arm CPU (e.g. Fairphone 2)

### ISSUE THREAD

**Issue by mohicanb** [LeanderBB/you-have-mail#31]
Hi, I tried to install on my Fairphone 2 equipped with /e/OS 1.14 R (Android 11).
F-Droid says there is no compatible version for my machine.
And the install through the /e/ App Lounge starts but fails.
Something missing ?

**Comment by LeanderBB** [comment]
Hey,

The install is probably failing due to the 32bit CPU. Currently, I only build the native code for 64bit arm/x86.

I would need to patch the fdroid build repo and some local build rules so the 32bit arm architecture is included.

Until then it won't be possible to install this on your phone.

**Comment by mohicanb** [comment]
Thank you. I have edited the title of the issue accordingly.

**Comment by LeanderBB** [comment]
Released with [v0.14.0](https://github.com/LeanderBB/you-have-mail/releases/tag/v0.14.0).

**Comment by mohicanb** [comment]
Tested ok on Fairphone 2 with /e/OS. Thanks a lot !
