### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by asebian** [LeanderBB/you-have-mail#32]
Hi,
unfortunately I can not log into my proton account using your app. A message pops up asking to complete a captcha which cannot be seen. I assume, proton is not happy with your app, as it  allows to use several free mail accounts without upgrading to payed subscription.

Cheers!

**Comment by LeanderBB** [comment]
Hey @asebian, it could be that proton has recently changed something in the way they handle the captcha verification. It was hard for me to trigger this in the past, so I can't promise I can fix this any time soon. 

It would still be helpful if you could export the logs so I can see if there is a clue there.

On another note, this application only provides new message notifications. It's not not a full fledged email application.

**Comment by asebian** [comment]
There is no rush. Thanks for sharing!
