### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by julianfairfax** [LeanderBB/you-have-mail#33]
In the Proton security settings, this app shows up as "Unknown". Is it possible to send the app's name as part of the logging in, so that it shows up as "You Have Mail" or something?

**Comment by LeanderBB** [comment]
Hey, I tried different names to identify the app, but they all lead to errors.

Either I use one or the existing app codes and be identified as one of the other clients (as well as be subject to special restrictions/behaviors associated with those ids or use Other (Unknown). Using anything else results in an error.

Unfortunately, it seems Proton is the one that controls this part so this is out of my hands.

**Comment by julianfairfax** [comment]
That's unfortunate.
