### ISSUE TITLE
[GrapheneOS 2023103100 on Pixel6] No notification at all 

### ISSUE THREAD

**Issue by houdini69** [LeanderBB/you-have-mail#34]
I am connected as indicated in the app (Status: Online) and on Proton web page as Unknown. The logs show nothing. How to debug?
.....
2023-11-02 18:43:40 | DEBUG | Received poll request
2023-11-02 18:43:40 | DEBUG | Polling account=xxxxxxxx@protonmail.com backend=Proton Mail
2023-11-02 18:43:40 | DEBUG | Proton Account xxxxxxxx@protonmail.com session refreshed

**Comment by LeanderBB** [comment]
Hey, I'm also running the latest GrapheneOS on a Pixel 6 and everything is working correctly for me. 

A couple of things to be aware of. The proton backend first initializes it's state on the first poll run. So if you received a new email at the same time the app initializes you will not be notified. 

I would recommend waiting or sending yourself a new email after a first poll round.

**Comment by houdini69** [comment]
Oh yes. I was in a bit of a hurry! I just received a notification of a test email. Thanks.
