### ISSUE TITLE
Publish on Google Play Store

### ISSUE THREAD

**Issue by Penknife0915** [LeanderBB/you-have-mail#36]
Requesting to add this app to the Play Store may seem counterintuitive, but it will bring benefits such as TOFU and fast updates. In the context of the app, this can be especially beneficial if Google Play only runs on the owner user and automatically updates non-owner user profiles.

You may also want to take a look at Accrescent:
https://accrescent.app/
https://accrescent.app/docs/index.html

**Comment by LeanderBB** [comment]
Hey @Penknife0915, thanks for the suggestion, but this is not something I'm currently interested in.

**Comment by LeanderBB** [comment]
I think [this](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/dev.lbeernaert.youhavemail.yml#L271) should be the hash you are looking for.
