### ISSUE TITLE
Support for tuta?

### ISSUE THREAD

**Issue by AzraelOmen021** [LeanderBB/you-have-mail#45]
Hi I love your app and was curious if there was a way to add support for Tuta ?

**Comment by LeanderBB** [comment]
Hey, thanks and happy you are enjoying it!

I would like to say that in theory, yes it should be possible. However, this is highly dependent on someone reverse engineering the Tuta API and filling in the right pieces in the code.

**Comment by pangratt12345** [comment]
hi,
It seems that Tuta Mail may use its own Push notification mechanism completely unrelated with Google. Tuta Nota replaced Google FCM (Firebase Cloud Messaging) with SSE (Server Sent Events) that doesn't communicate with Google servers at all
https://f-droid.org/en/2018/09/03/replacing-gcm-in-tutanota.html

I also checked this on my smartphone with all apps and files related to Google uninstalled and erased from it and Tuta Mail still manages to send its own push notifications about mails to this smartphone while Proton Mail doesn't notify about incoming mails on this smartphone (unless I install YouHaveMail application on it)

So I think that implementing additional functionality of YouHaveMail application to receive notifications from Tuta Mail might be unnecessary and optional

**Comment by LeanderBB** [comment]
Thanks @pangratt12345 for the research, will mark the issue as resolved since it seems very unlikely people will install the YouHaveMail without the Tutanota app.
