### ISSUE TITLE
Webpage out of date error

### ISSUE THREAD

**Issue by cx76k** [LeanderBB/you-have-mail#6]
App version: 0.4.0
Device: Google Pixel 4a
OS: GrapheneOS, Android 13

Today, I started getting errors about the website being out of date as seen in the screenshot:
![Screenshot_20230404-102844_1](https://user-images.githubusercontent.com/106716674/229826393-2c3819e9-2426-4d81-96af-56525b91a1ae.png)

This first occurred after being continuously logged in for an extended period. The error notifications kept coming with no refresh option. After an uninstall/reinstall, I am no longer able to login due to the error.

By the way, I've been enjoying the app a lot!

**Comment by LeanderBB** [comment]
Hey, thanks for the report & happy to hear :).

I also experienced this issue today. Unfortunately, I'm currently on holiday. Once I return I'll investigate what's going on.

**Comment by LeanderBB** [comment]
I have just released version 0.4.1, which addresses the issue.
