### ISSUE TITLE
CAPTCHA

### ISSUE THREAD

**Issue by julianfairfax** [LeanderBB/you-have-mail#7]
App shows a CAPTCHA error when I try to login. Maybe this because I have 2FA?

![IMG_20230422_190000](https://user-images.githubusercontent.com/43753131/233797157-675e26f4-730e-4ae2-bb8e-5a2d8d3a7aa1.jpg)

**Comment by LeanderBB** [comment]
Hey Julian,

I have tested the app with 2FA accounts (TOTP only) and I have never seen this specific error message before.

I will try to see if I can reproduce this locally somehow. However, I would like to make it clear that if I can't reproduce this, I will be unable to address the problem.

When you log into the proton website, do you also get captcha verification requests? If not, I would try to get the your phone to be as close to that network environment as possible and try again in hopes that you can skip the verification.

**Comment by LeanderBB** [comment]
Interesting, thanks for the info. Once I'm back I'll try the same approach and see what happens.

**Comment by LeanderBB** [comment]
@julianfairfax I have published v0.5.0 which has the **Proton Mail V-Other** backend. This uses `Other` as the version string. 

Let me know if that fixes the issue for you.

**Comment by LeanderBB** [comment]
Hey. Totally agree. I plan to address this when I finish with a collection of other improvements :).

-------- Original Message --------
