### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by julianfairfax** [LeanderBB/you-have-mail#8]
Is there any chance of adding a preview to the app's notifications? It would be nice to see who an email is from, its subject, etc, without opening Proton Mail.

**Comment by LeanderBB** [comment]
In theory, I think this should be possible.

I haven't gone that route at the moment, since I can't control the the ProtonMail app to open that specific message when you would click on the notification.

If there are more people interested I can look into adding this.

**Comment by calhix** [comment]
Similar but different/maybe simpler request, is it possible to have it at least open Proton Mail when clicking on the notification?

**Comment by LeanderBB** [comment]
This should work currently. When you click on the notification that says you have X new messages for the account it opens the ProtonMail app.

**Comment by calhix** [comment]
Interesting, hasn't worked for me so far for me (app installed via Izzy). I'll report back when I can reverify.

**Comment by calhix** [comment]
Same result, I tried clicking on the notification a bunch of times but it doesn't do anything. Should I open a new issue?

**Comment by LeanderBB** [comment]
Yes, please open another ticket for this. Can you also clarify in the ticket what the "Izzy" source is (first time I hear about it) and what version of Android you are running on your device?

The source has no effect on the notification code. I have tested the code on Android 12 and 13 and everything works for me with GrapheneOS.

**Comment by calhix** [comment]
Apologies, not Izzy but from here as mentioned in a closed issue: https://gitlab.com/julianfairfax/fdroid-repo

**Comment by LeanderBB** [comment]
@julianfairfax v0.6.0 now includes the last 6 messages that were received. You can view this info by expanding the message.
