### ISSUE TITLE
Notification doesn't open ProtonMail app

### ISSUE THREAD

**Issue by calhix** [LeanderBB/you-have-mail#9]
This is on the One Plus 8 Pro running the latest LineageOS (Android 13). You Have Mail app installed from https://gitlab.com/julianfairfax/fdroid-repo. Proton Mail app installed from IzzyOnDroid repo from the F-Droid (Neo) store.

**Comment by LeanderBB** [comment]
I just released v0.5.1, which should fix the issue.
